# Generated by Django 3.1.4 on 2021-02-16 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('product_name', models.CharField(blank=True, max_length=225, null=True)),
                ('product_code', models.CharField(blank=True, max_length=225, null=True)),
                ('product_images', models.ImageField(blank=True, default='default_product.png', null=True, upload_to='product_img')),
                ('product_mfg_date', models.DateField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
